### ISSUE TITLE
Limit arm motion based on sensors

### ISSUE THREAD

**Issue by rtfoley** [frc5687/2016-Outlier2#111] opened 2016-02-16 20:50 UTC
We should limit the arm motion using the potentiometer, so that the operators don't try and move the arms past any physical limitations.

**Comment by rtfoley** [comment] 2016-02-16 20:50
This will require some trial and error with the actual hardware, so that the appropriate limits can be determined.

**Comment by wilstenholme** [comment] 2016-02-17 03:35
Closed due to duplicate of #113

**Closed as completed by wilstenholme** 2016-02-17 03:35 UTC
Labels: priority:critical, arms
